export { Bio } from './Bio'
export { Contacts } from './Contacts'
export { Developed } from './Developed'
export { Header } from './Header'
export { Jobs } from './Jobs'
export { Skills } from './Skills'
export { Technologies } from './Technologies'
