// Generated by `npm run cv:snapshot`. Do not edit by hand.
//
// A build-time copy of the CV so the site never depends on the API being up.
// Typed against Cv, so a change in the API's shape breaks the build here.

import type { Cv, Locale } from "./cv-api";

export const cvSnapshot: Record<Locale, Cv> = {
	en: {
		name: "Kirill Petunin",
		headline: "Senior Frontend / Full-stack Engineer / Team Lead",
		description:
			"Senior engineer with 7+ years of experience building high-scale web applications. Specialises in React, TypeScript and micro-frontend architectures for fintech and e-commerce. At T1 Innotech architected a cryptocurrency platform targeting 99.9% uptime and 200% better scalability. While leading a team at Grid Dynamics, cut enterprise app load time from 10s to 2s and improved payment flows handling 1M+ daily transactions. Also founded and solo-operates a subscription SaaS with 150+ paying customers, owning architecture, payments, infrastructure and growth end to end.",
		location: "Kazan, Russia",
		availability: "Worldwide, remote",
		email: "kpetunin@icloud.com",
		phone: "+79956727623",
		website: "https://cv.holakirr.com",
		yearsOfExperience: 8,
		socialLinks: [
			{
				platform: "GITHUB",
				label: "GitHub",
				url: "https://github.com/holakirr",
			},
			{
				platform: "LINKEDIN",
				label: "LinkedIn",
				url: "https://www.linkedin.com/in/holakirr/",
			},
			{
				platform: "TELEGRAM",
				label: "Telegram",
				url: "https://t.me/holakirr",
			},
			{
				platform: "INSTAGRAM",
				label: "Instagram",
				url: "https://instagram.com/holakirr",
			},
			{
				platform: "WEBSITE",
				label: "cv.holakirr.com",
				url: "https://cv.holakirr.com",
			},
		],
		skills: [
			{
				name: "TypeScript",
				category: "FRONTEND",
			},
			{
				name: "JavaScript (ES6+)",
				category: "FRONTEND",
			},
			{
				name: "React",
				category: "FRONTEND",
			},
			{
				name: "Next.js",
				category: "FRONTEND",
			},
			{
				name: "Remix",
				category: "FRONTEND",
			},
			{
				name: "Ember.js",
				category: "FRONTEND",
			},
			{
				name: "HTML5",
				category: "FRONTEND",
			},
			{
				name: "CSS3",
				category: "FRONTEND",
			},
			{
				name: "TailwindCSS",
				category: "FRONTEND",
			},
			{
				name: "Styled Components",
				category: "FRONTEND",
			},
			{
				name: "Node.js",
				category: "BACKEND",
			},
			{
				name: "NestJS",
				category: "BACKEND",
			},
			{
				name: "Express.js",
				category: "BACKEND",
			},
			{
				name: "GraphQL",
				category: "BACKEND",
			},
			{
				name: "REST API",
				category: "BACKEND",
			},
			{
				name: "Microservices",
				category: "BACKEND",
			},
			{
				name: "BullMQ",
				category: "BACKEND",
			},
			{
				name: "PostgreSQL",
				category: "DATABASE",
			},
			{
				name: "Prisma",
				category: "DATABASE",
			},
			{
				name: "Redis",
				category: "DATABASE",
			},
			{
				name: "MongoDB",
				category: "DATABASE",
			},
			{
				name: "Git",
				category: "DEVOPS",
			},
			{
				name: "Docker",
				category: "DEVOPS",
			},
			{
				name: "CI/CD",
				category: "DEVOPS",
			},
			{
				name: "GitHub Actions",
				category: "DEVOPS",
			},
			{
				name: "Webpack",
				category: "DEVOPS",
			},
			{
				name: "Vite",
				category: "DEVOPS",
			},
			{
				name: "Bun",
				category: "DEVOPS",
			},
			{
				name: "Vitest",
				category: "TESTING",
			},
			{
				name: "Jest",
				category: "TESTING",
			},
			{
				name: "React Testing Library",
				category: "TESTING",
			},
			{
				name: "Playwright",
				category: "TESTING",
			},
			{
				name: "Team Leadership",
				category: "SOFT",
			},
			{
				name: "Mentoring",
				category: "SOFT",
			},
			{
				name: "Code Review",
				category: "SOFT",
			},
			{
				name: "Agile / Scrum",
				category: "SOFT",
			},
		],
		experience: [
			{
				company: "VPN Subscription Service",
				position: "Founder & Engineer",
				period: "May 2026 — Present",
				isCurrent: true,
				startDate: "2026-05-01T00:00:00.000Z",
				endDate: null,
				summary:
					"Commercial VPN subscription service built and run solo — 150+ paying subscribers, in production since May 2026.",
				achievements: [
					{
						description:
							"NestJS core API (PostgreSQL, Prisma, Redis, BullMQ), a Next.js landing with web payments, a TypeScript Telegram bot.",
					},
					{
						description:
							"Recurring billing with idempotent payment webhooks and automatic retries.",
					},
					{
						description:
							"CI/CD, uptime monitoring, hourly backups and 425+ automated tests on infrastructure I run myself.",
					},
				],
			},
			{
				company: "T1 Innotech",
				position: "Senior Frontend Engineer",
				period: "Nov 2024 — Present",
				isCurrent: true,
				startDate: "2024-11-01T00:00:00.000Z",
				endDate: null,
				summary:
					"Cryptocurrency platform on React, Remix, TypeScript and Node.js, against a 99.9% uptime target.",
				achievements: [
					{
						description:
							"Led the migration from a monolithic frontend to BFF + micro-frontends: 200% better scalability, 20% faster deploys.",
					},
					{
						description:
							"Built real-time transaction processing with security and performance as the hard constraints.",
					},
				],
			},
			{
				company: "Grid Dynamics",
				position: "Senior Frontend Developer / Team Lead",
				period: "Jun 2021 — Aug 2024",
				isCurrent: false,
				startDate: "2021-06-01T00:00:00.000Z",
				endDate: "2024-08-01T00:00:00.000Z",
				summary: "Fortune 300 client project, leading a team of 5 engineers.",
				achievements: [
					{
						description:
							"Led 5 engineers, shipped a UI component library and a large-scale dependency modernization.",
					},
					{
						description:
							"Cut enterprise app load time from 10s to 2s — lazy loading, table virtualization, render optimizations.",
					},
					{
						description:
							"Reworked payment flows for a global e-commerce brand handling 1M+ daily transactions.",
					},
				],
			},
			{
				company: "Globus-IT",
				position: "Frontend Developer",
				period: "Sep 2020 — Jun 2021",
				isCurrent: false,
				startDate: "2020-09-01T00:00:00.000Z",
				endDate: "2021-06-01T00:00:00.000Z",
				summary: "Banking products for major Russian financial institutions.",
				achievements: [
					{
						description:
							"Admin panel for a major bank (500+ daily users) and a mobile investment app (10K+ users), at 85%+ test coverage.",
					},
				],
			},
			{
				company: "Chitai Gorod",
				position: "Frontend Developer",
				period: "Feb 2020 — Sep 2020",
				isCurrent: false,
				startDate: "2020-02-01T00:00:00.000Z",
				endDate: "2020-09-01T00:00:00.000Z",
				summary: "E-commerce features for the largest Russian book retailer.",
				achievements: [
					{
						description: "Led analysis and delivery of a new payment method, shipped on schedule.",
					},
				],
			},
			{
				company: "Rerise",
				position: "Web Developer",
				period: "Sep 2018 — Feb 2020",
				isCurrent: false,
				startDate: "2018-09-01T00:00:00.000Z",
				endDate: "2020-02-01T00:00:00.000Z",
				summary: "End-to-end website delivery for agency clients.",
				achievements: [
					{
						description:
							"Full lifecycle from requirements to deployment — JavaScript, SCSS/Sass, WordPress, PHP.",
					},
				],
			},
		],
		projects: [
			{
				name: "Backgammon",
				description:
					"Online backgammon — long and short — with live matches over SSE, three tournament formats and Elo rating. The server owns the dice and validates every move with the rules engine the browser uses to highlight them.",
				url: "https://backgammon.holakirr.com",
				repositoryUrl: null,
				demoUrl: null,
				stack: ["Next.js", "TypeScript", "PostgreSQL", "Drizzle", "SSE", "Docker", "Caddy"],
				featured: true,
			},
			{
				name: "Snow UI",
				description: "React component library published to npm, documented with Storybook.",
				url: "https://www.npmjs.com/package/@holakirr/snow-ui",
				repositoryUrl: "https://github.com/holakirr/snow-ui",
				demoUrl: null,
				stack: ["React", "TypeScript", "Storybook", "Vite"],
				featured: true,
			},
			{
				name: "Snow UI Icons",
				description: "Companion icon set for Snow UI, published to npm with a live Storybook.",
				url: "https://www.npmjs.com/package/@holakirr/snow-ui-icons",
				repositoryUrl: "https://github.com/holakirr/snow-ui-icons",
				demoUrl: "https://snow-ui-icons.holakirr.com/",
				stack: ["React", "TypeScript", "SVG", "Storybook"],
				featured: true,
			},
			{
				name: "VPN Subscription Service",
				description:
					"Commercial VPN subscription service with recurring billing, run solo in production for 150+ paying subscribers.",
				url: "https://t.me/holakirr_vpn_bot",
				repositoryUrl: null,
				demoUrl: null,
				stack: ["NestJS", "PostgreSQL", "Prisma", "Redis", "BullMQ", "Next.js", "Docker"],
				featured: true,
			},
		],
		certifications: [
			{
				name: "Apollo Graph Developer",
				issuer: "Apollo GraphQL",
				url: "https://www.apollographql.com/tutorials/certifications/995acb9d-9aae-431b-a882-3e3f0a2e8e7a",
			},
			{
				name: "NestJS",
				issuer: "Udemy",
				url: "https://ude.my/UC-b0a39fe8-2502-4d9a-aa7e-527e3c87d7f0",
			},
			{
				name: "Node.js",
				issuer: "Udemy",
				url: "https://ude.my/UC-7c27bd0d-8d74-40c2-ad2c-c7fe033d300b",
			},
			{
				name: "Node.js + Mongo + GraphQL + Express + MySQL",
				issuer: "Udemy",
				url: "https://ude.my/UC-d26bce27-203a-4605-bc55-7bb6b49f91c4",
			},
			{
				name: "React + Next.js",
				issuer: "Udemy",
				url: "https://ude.my/UC-252a2d36-5f14-41df-a93a-02d6bc4e2bef",
			},
			{
				name: "GoLang",
				issuer: "Udemy",
				url: "https://ude.my/UC-e3899d5c-6bea-460e-89e6-745468715575",
			},
		],
		languages: [
			{
				name: "Russian",
				level: "NATIVE",
			},
			{
				name: "English",
				level: "B2",
			},
		],
	},
	ru: {
		name: "Kirill Petunin",
		headline: "Senior Frontend / Full-stack инженер / тимлид",
		description:
			"Senior-инженер с опытом более 7 лет в разработке высоконагруженных веб-приложений. Специализируюсь на React, TypeScript и микрофронтендах для финтеха и электронной коммерции. В T1 Innotech спроектировал криптовалютную платформу с целевым аптаймом 99,9% и ростом масштабируемости на 200%. Руководя командой в Grid Dynamics, сократил время загрузки корпоративного приложения с 10 до 2 секунд и доработал платёжные сценарии, обслуживающие более 1 млн транзакций в день. Помимо найма — основал и в одиночку веду подписочный SaaS со 150+ платящими клиентами, отвечая за архитектуру, платежи, инфраструктуру и рост.",
		location: "Казань, Россия",
		availability: "Удалённо, по всему миру",
		email: "kpetunin@icloud.com",
		phone: "+79956727623",
		website: "https://cv.holakirr.com",
		yearsOfExperience: 8,
		socialLinks: [
			{
				platform: "GITHUB",
				label: "GitHub",
				url: "https://github.com/holakirr",
			},
			{
				platform: "LINKEDIN",
				label: "LinkedIn",
				url: "https://www.linkedin.com/in/holakirr/",
			},
			{
				platform: "TELEGRAM",
				label: "Telegram",
				url: "https://t.me/holakirr",
			},
			{
				platform: "INSTAGRAM",
				label: "Instagram",
				url: "https://instagram.com/holakirr",
			},
			{
				platform: "WEBSITE",
				label: "cv.holakirr.com",
				url: "https://cv.holakirr.com",
			},
		],
		skills: [
			{
				name: "TypeScript",
				category: "FRONTEND",
			},
			{
				name: "JavaScript (ES6+)",
				category: "FRONTEND",
			},
			{
				name: "React",
				category: "FRONTEND",
			},
			{
				name: "Next.js",
				category: "FRONTEND",
			},
			{
				name: "Remix",
				category: "FRONTEND",
			},
			{
				name: "Ember.js",
				category: "FRONTEND",
			},
			{
				name: "HTML5",
				category: "FRONTEND",
			},
			{
				name: "CSS3",
				category: "FRONTEND",
			},
			{
				name: "TailwindCSS",
				category: "FRONTEND",
			},
			{
				name: "Styled Components",
				category: "FRONTEND",
			},
			{
				name: "Node.js",
				category: "BACKEND",
			},
			{
				name: "NestJS",
				category: "BACKEND",
			},
			{
				name: "Express.js",
				category: "BACKEND",
			},
			{
				name: "GraphQL",
				category: "BACKEND",
			},
			{
				name: "REST API",
				category: "BACKEND",
			},
			{
				name: "Микросервисы",
				category: "BACKEND",
			},
			{
				name: "BullMQ",
				category: "BACKEND",
			},
			{
				name: "PostgreSQL",
				category: "DATABASE",
			},
			{
				name: "Prisma",
				category: "DATABASE",
			},
			{
				name: "Redis",
				category: "DATABASE",
			},
			{
				name: "MongoDB",
				category: "DATABASE",
			},
			{
				name: "Git",
				category: "DEVOPS",
			},
			{
				name: "Docker",
				category: "DEVOPS",
			},
			{
				name: "CI/CD",
				category: "DEVOPS",
			},
			{
				name: "GitHub Actions",
				category: "DEVOPS",
			},
			{
				name: "Webpack",
				category: "DEVOPS",
			},
			{
				name: "Vite",
				category: "DEVOPS",
			},
			{
				name: "Bun",
				category: "DEVOPS",
			},
			{
				name: "Vitest",
				category: "TESTING",
			},
			{
				name: "Jest",
				category: "TESTING",
			},
			{
				name: "React Testing Library",
				category: "TESTING",
			},
			{
				name: "Playwright",
				category: "TESTING",
			},
			{
				name: "Руководство командой",
				category: "SOFT",
			},
			{
				name: "Менторство",
				category: "SOFT",
			},
			{
				name: "Код-ревью",
				category: "SOFT",
			},
			{
				name: "Agile / Scrum",
				category: "SOFT",
			},
		],
		experience: [
			{
				company: "VPN Subscription Service",
				position: "Основатель и инженер",
				period: "май 2026 — Сейчас",
				isCurrent: true,
				startDate: "2026-05-01T00:00:00.000Z",
				endDate: null,
				summary:
					"Коммерческий VPN-сервис по подписке, построенный и обслуживаемый в одиночку: 150+ платящих подписчиков, в продакшене с мая 2026 года.",
				achievements: [
					{
						description:
							"Ядро API на NestJS (PostgreSQL, Prisma, Redis, BullMQ), лендинг на Next.js с приёмом платежей, Telegram-бот на TypeScript.",
					},
					{
						description:
							"Регулярные списания с идемпотентными платёжными вебхуками и автоматическими повторами.",
					},
					{
						description:
							"CI/CD, мониторинг доступности, ежечасные бэкапы и 425+ автотестов на инфраструктуре, которую веду сам.",
					},
				],
			},
			{
				company: "T1 Innotech",
				position: "Senior Frontend-инженер",
				period: "нояб. 2024 — Сейчас",
				isCurrent: true,
				startDate: "2024-11-01T00:00:00.000Z",
				endDate: null,
				summary:
					"Криптовалютная платформа на React, Remix, TypeScript и Node.js с целевым аптаймом 99,9%.",
				achievements: [
					{
						description:
							"Провёл переход от монолитного фронтенда к BFF + микрофронтендам: масштабируемость +200%, время выката −20%.",
					},
					{
						description:
							"Построил обработку транзакций в реальном времени, где безопасность и производительность — жёсткие ограничения.",
					},
				],
			},
			{
				company: "Grid Dynamics",
				position: "Senior Frontend-разработчик / тимлид",
				period: "июнь 2021 — авг. 2024",
				isCurrent: false,
				startDate: "2021-06-01T00:00:00.000Z",
				endDate: "2024-08-01T00:00:00.000Z",
				summary: "Проект для клиента из Fortune 300, руководство командой из 5 инженеров.",
				achievements: [
					{
						description:
							"Руководил пятью инженерами, внедрил библиотеку UI-компонентов и обновил зависимости в масштабе проекта.",
					},
					{
						description:
							"Сократил загрузку корпоративного приложения с 10 до 2 секунд: ленивая загрузка, виртуализация таблиц, оптимизация рендера.",
					},
					{
						description:
							"Переработал платёжные сценарии международного e-commerce бренда с 1 млн+ транзакций в день.",
					},
				],
			},
			{
				company: "Globus-IT",
				position: "Frontend-разработчик",
				period: "сент. 2020 — июнь 2021",
				isCurrent: false,
				startDate: "2020-09-01T00:00:00.000Z",
				endDate: "2021-06-01T00:00:00.000Z",
				summary: "Банковские продукты для крупных российских финансовых организаций.",
				achievements: [
					{
						description:
							"Админ-панель крупного банка (500+ пользователей в день) и мобильное инвестприложение (10K+ пользователей), покрытие тестами 85%+.",
					},
				],
			},
			{
				company: "Chitai Gorod",
				position: "Frontend-разработчик",
				period: "февр. 2020 — сент. 2020",
				isCurrent: false,
				startDate: "2020-02-01T00:00:00.000Z",
				endDate: "2020-09-01T00:00:00.000Z",
				summary: "Функциональность интернет-магазина крупнейшей книжной сети России.",
				achievements: [
					{
						description: "Вёл анализ и реализацию нового способа оплаты, выпустил в срок.",
					},
				],
			},
			{
				company: "Rerise",
				position: "Веб-разработчик",
				period: "сент. 2018 — февр. 2020",
				isCurrent: false,
				startDate: "2018-09-01T00:00:00.000Z",
				endDate: "2020-02-01T00:00:00.000Z",
				summary: "Разработка сайтов для клиентов агентства под ключ.",
				achievements: [
					{
						description:
							"Полный цикл от требований до развёртывания: JavaScript, SCSS/Sass, WordPress, PHP.",
					},
				],
			},
		],
		projects: [
			{
				name: "Backgammon",
				description:
					"Онлайн-нарды, длинные и короткие: партии в реальном времени по SSE, три формата турниров и рейтинг Elo. Кубики бросает только сервер, ходы он же валидирует тем движком правил, которым браузер их подсвечивает.",
				url: "https://backgammon.holakirr.com",
				repositoryUrl: null,
				demoUrl: null,
				stack: ["Next.js", "TypeScript", "PostgreSQL", "Drizzle", "SSE", "Docker", "Caddy"],
				featured: true,
			},
			{
				name: "Snow UI",
				description:
					"Библиотека React-компонентов, опубликованная в npm и задокументированная в Storybook.",
				url: "https://www.npmjs.com/package/@holakirr/snow-ui",
				repositoryUrl: "https://github.com/holakirr/snow-ui",
				demoUrl: null,
				stack: ["React", "TypeScript", "Storybook", "Vite"],
				featured: true,
			},
			{
				name: "Snow UI Icons",
				description: "Набор иконок к Snow UI, опубликованный в npm, с живым Storybook.",
				url: "https://www.npmjs.com/package/@holakirr/snow-ui-icons",
				repositoryUrl: "https://github.com/holakirr/snow-ui-icons",
				demoUrl: "https://snow-ui-icons.holakirr.com/",
				stack: ["React", "TypeScript", "SVG", "Storybook"],
				featured: true,
			},
			{
				name: "VPN Subscription Service",
				description:
					"Коммерческий VPN-сервис по подписке с регулярными списаниями; в одиночку веду в продакшене для 150+ платящих подписчиков.",
				url: "https://t.me/holakirr_vpn_bot",
				repositoryUrl: null,
				demoUrl: null,
				stack: ["NestJS", "PostgreSQL", "Prisma", "Redis", "BullMQ", "Next.js", "Docker"],
				featured: true,
			},
		],
		certifications: [
			{
				name: "Apollo Graph Developer",
				issuer: "Apollo GraphQL",
				url: "https://www.apollographql.com/tutorials/certifications/995acb9d-9aae-431b-a882-3e3f0a2e8e7a",
			},
			{
				name: "NestJS",
				issuer: "Udemy",
				url: "https://ude.my/UC-b0a39fe8-2502-4d9a-aa7e-527e3c87d7f0",
			},
			{
				name: "Node.js",
				issuer: "Udemy",
				url: "https://ude.my/UC-7c27bd0d-8d74-40c2-ad2c-c7fe033d300b",
			},
			{
				name: "Node.js + Mongo + GraphQL + Express + MySQL",
				issuer: "Udemy",
				url: "https://ude.my/UC-d26bce27-203a-4605-bc55-7bb6b49f91c4",
			},
			{
				name: "React + Next.js",
				issuer: "Udemy",
				url: "https://ude.my/UC-252a2d36-5f14-41df-a93a-02d6bc4e2bef",
			},
			{
				name: "GoLang",
				issuer: "Udemy",
				url: "https://ude.my/UC-e3899d5c-6bea-460e-89e6-745468715575",
			},
		],
		languages: [
			{
				name: "Русский",
				level: "NATIVE",
			},
			{
				name: "Английский",
				level: "B2",
			},
		],
	},
};
