export { Github as GithubIcon } from "./Github";
export { Instagram as InstagramIcon } from "./Instagram";
export { LinkedIn as LinkedInIcon } from "./LinkedIn";
export { Mail as MailIcon } from "./Mail";
export { Npm as NpmIcon } from "./Npm";
export { Phone as PhoneIcon } from "./Phone";
export { StoryBook as StoryBookIcon } from "./StoryBook";
export { Telegram as TelegramIcon } from "./Telegram";
export { Web as WebIcon } from "./Web";
