#!/usr/bin/env node
// Refreshes lib/cv-snapshot.ts from the GraphQL API.
//
// The site builds from the snapshot, so this is the only step that needs the
// API running. Run it after editing cv-data.ts and reseeding, then commit the
// result — CV changes show up as a reviewable diff.
//
// It emits TypeScript rather than JSON on purpose: the file is typed as
// Record<Locale, Cv>, so if the API's shape drifts, `next build` fails loudly
// instead of shipping a page with missing fields.

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { fetchCvFromApi } from "../lib/cv-api.ts";

const API_URL = process.env.CV_API_URL ?? "http://localhost:3000/graphql";
const LOCALES = ["en", "ru"];
const TARGET = resolve(import.meta.dirname, "../lib/cv-snapshot.ts");

const entries = await Promise.all(
	LOCALES.map(async (locale) => [locale, await fetchCvFromApi(locale, API_URL)])
);

const header = `// Generated by \`npm run cv:snapshot\`. Do not edit by hand.
//
// A build-time copy of the CV so the site never depends on the API being up.
// Typed against Cv, so a change in the API's shape breaks the build here.

import type { Cv, Locale } from "./cv-api";

export const cvSnapshot: Record<Locale, Cv> = `;

await writeFile(TARGET, `${header}${JSON.stringify(Object.fromEntries(entries), null, "\t")};\n`);

for (const [locale, cv] of entries) {
	console.log(
		`  ${locale}: ${cv.experience.length} places, ` +
			`${cv.experience.reduce((n, e) => n + e.achievements.length, 0)} achievements, ` +
			`${cv.skills.length} skills, ${cv.projects.length} projects`
	);
}

console.log(`\nWrote ${TARGET} from ${API_URL}`);
